# yaml-language-server: $id=https://json.schemastore.org/github-workflow.json
# see more - https://developers.redhat.com/blog/2020/11/25/how-to-configure-yaml-schema-to-make-editing-files-easier
name: CMake Build and Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/geugenm/diploma:latest
      options: --user 1001 # Run container as non-root user
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy
        run: cmake --workflow --preset deploy

      - name: Collect artifacts
        run: |
          mkdir -p artifacts
          cp build/release/cpack/*.tar.gz artifacts/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: |
            artifacts/*.tar.gz
