name: CMake Build and Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: fedora-latest # Correctly specify Fedora as the base

    container: ghcr.io/geugenm/diploma:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure (Release)
        run: cmake --preset release

      - name: Build (Release)
        run: cmake --build --preset release

      - name: Package (Release TGZ)
        run: cpack --preset default

      - name: Collect artifacts
        run: |
          mkdir -p artifacts
          cp build/release/cpack/*.tar.gz artifacts/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: |
            artifacts/*.tar.gz
            build/release/compile_commands.json
